/* tslint:disable */
/* eslint-disable */
/**
 * EGR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompanyDtoPagedResult,
  DropdownModel,
} from '../models/index';

export interface ApiCompanyPageGetRequest {
    companyName?: string;
    companyGroupId?: number;
    activeFlag?: boolean;
    pageNumber?: number;
    pageSize?: number;
    sortBy?: string;
    sortDesc?: boolean;
}

/**
 * CompanyApi - interface
 * 
 * @export
 * @interface CompanyApiInterface
 */
export interface CompanyApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApiInterface
     */
    apiCompanyDropdownGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DropdownModel>>>;

    /**
     */
    apiCompanyDropdownGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DropdownModel>>;

    /**
     * 
     * @param {string} [companyName] 
     * @param {number} [companyGroupId] 
     * @param {boolean} [activeFlag] 
     * @param {number} [pageNumber] 
     * @param {number} [pageSize] 
     * @param {string} [sortBy] 
     * @param {boolean} [sortDesc] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApiInterface
     */
    apiCompanyPageGetRaw(requestParameters: ApiCompanyPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyDtoPagedResult>>;

    /**
     */
    apiCompanyPageGet(requestParameters: ApiCompanyPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyDtoPagedResult>;

}

/**
 * 
 */
export class CompanyApi extends runtime.BaseAPI implements CompanyApiInterface {

    /**
     */
    async apiCompanyDropdownGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DropdownModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/Company/dropdown`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiCompanyDropdownGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DropdownModel>> {
        const response = await this.apiCompanyDropdownGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCompanyPageGetRaw(requestParameters: ApiCompanyPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyDtoPagedResult>> {
        const queryParameters: any = {};

        if (requestParameters['companyName'] != null) {
            queryParameters['CompanyName'] = requestParameters['companyName'];
        }

        if (requestParameters['companyGroupId'] != null) {
            queryParameters['CompanyGroupId'] = requestParameters['companyGroupId'];
        }

        if (requestParameters['activeFlag'] != null) {
            queryParameters['ActiveFlag'] = requestParameters['activeFlag'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['SortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDesc'] != null) {
            queryParameters['SortDesc'] = requestParameters['sortDesc'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/Company/page`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiCompanyPageGet(requestParameters: ApiCompanyPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyDtoPagedResult> {
        const response = await this.apiCompanyPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
