/* tslint:disable */
/* eslint-disable */
/**
 * EGR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserDTO,
  UserDTOPagedResult,
} from '../models/index';

export interface ApiUserPagingGetRequest {
    username?: string;
    firstName?: string;
    lastName?: string;
    activeFlag?: boolean;
    pageNumber?: number;
    pageSize?: number;
    sortBy?: string;
    sortDesc?: boolean;
}

/**
 * UserApi - interface
 * 
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
    /**
     * 
     * @param {string} [username] 
     * @param {string} [firstName] 
     * @param {string} [lastName] 
     * @param {boolean} [activeFlag] 
     * @param {number} [pageNumber] 
     * @param {number} [pageSize] 
     * @param {string} [sortBy] 
     * @param {boolean} [sortDesc] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    apiUserPagingGetRaw(requestParameters: ApiUserPagingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTOPagedResult>>;

    /**
     */
    apiUserPagingGet(requestParameters: ApiUserPagingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTOPagedResult>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    apiUserSigninPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>>;

    /**
     */
    apiUserSigninPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO>;

}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI implements UserApiInterface {

    /**
     */
    async apiUserPagingGetRaw(requestParameters: ApiUserPagingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTOPagedResult>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['Username'] = requestParameters['username'];
        }

        if (requestParameters['firstName'] != null) {
            queryParameters['FirstName'] = requestParameters['firstName'];
        }

        if (requestParameters['lastName'] != null) {
            queryParameters['LastName'] = requestParameters['lastName'];
        }

        if (requestParameters['activeFlag'] != null) {
            queryParameters['ActiveFlag'] = requestParameters['activeFlag'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['PageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['SortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDesc'] != null) {
            queryParameters['SortDesc'] = requestParameters['sortDesc'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/User/paging`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiUserPagingGet(requestParameters: ApiUserPagingGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTOPagedResult> {
        const response = await this.apiUserPagingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiUserSigninPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = await this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/User/signin`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiUserSigninPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO> {
        const response = await this.apiUserSigninPostRaw(initOverrides);
        return await response.value();
    }

}
